site_name: "Chaos Laboratory"
site_description: "Chaos Laboratory Research Group Website"
site_author: "Chaos Laboratory Team"

extra_css:
  - css/extra.css
  - css/random-youtube.css
extra_javascript:
  - js/random-youtube.js

# Repository
repo_name: chaos-polymtl/lethe
repo_url: https://github.com/chaos-polymtl/lethe

# Theme configuration
theme:
  name: material
  logo: assets/chaos_logo_white_without_bkg.png
  favicon: assets/chaos_logo_black_without_bkg.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono


# Navigation
nav:
  - Home: index.md
  - News: news.md
  - Team: team.md
  - Research: research.md
  - Software: software.md
  - Publications: publications.md
  - Blog: blog.md
  - Teaching: teaching.md

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search



# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaos-polymtl
    - icon: fontawesome/solid/star
      link: https://github.com/chaos-polymtl/lethe/stargazers
    - icon: fontawesome/solid/code-branch
      link: https://github.com/chaos-polymtl/lethe/network/members