site_name: Chaos Laboratory
site_description: Chaos Laboratory Research Group Website
site_author: Chaos Laboratory Team

# Repository
repo_name: chaos-polymtl/chaos-lab
repo_url: https://github.com/chaos-polymtl/chaos-lab

# Theme configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Navigation
nav:
  - Home: index.md
  - Team: team.md
  - Research: research.md
  - Software: software.md
  - Publications: publications.md
  - Blog: blog.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaos-polymtl
