name: "Deploy Website"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install "mkdocs==1.6.1" "mkdocs-material>=9.0" "markdown-include" "pymdown-extensions" "Markdown<3.7"
      - run: mkdocs gh-deploy --clean --force